### ISSUE TITLE
alldebrid

### ISSUE THREAD

**Issue by redx113** [CaptainMishan/RDRSS#2]
Hi,

This is not really an issue, but I guess more of a feature request. Is there a way you can fork this to work with alldebrid or can I edit the python script to somehow also send magnets into alldebrid.com? 

This works a treat with realdebrid, so I appreciate it if can give some insight into this

**Comment by mishpajz** [comment]
Support for other services is not planned, the script only focuses on Real-Debrid, although adaptation to other services (if the service provides an API) is certainly not complicated.
