### ISSUE TITLE
small error when finishing executing the script with a specific RSS

### ISSUE THREAD

**Issue by Root-FTW** [CaptainMishan/RDRSS#4]
I am using the following RSS feed, everything works perfect:
![2022-07-18 13_05_48](https://user-images.githubusercontent.com/108767514/179608082-81b01c50-80f3-4ca7-a292-5de1ed1a30a7.png)

but then this happens, I think that's when it ends:
![2022-07-18 13_05_58](https://user-images.githubusercontent.com/108767514/179608183-0697a6f6-b89f-4da7-9d25-2d8655820659.png)

the RSS feed I'm using is this:
https://torrentgalaxy.to/rss?magnet&user=7847

Could you fix this error please? :)

And would it also be possible to add more than 1 RSS?
I currently have 2 RSS feeds, it would be great to be able to add both

**Comment by mishpajz** [comment]
https://github.com/mishpajz/RDRSS/releases/tag/2.5
